### ISSUE TITLE
Alignement à partir du confinement total

### ISSUE THREAD

**Issue by Mat-GH** [rozierguillaume/covid-19#1]
Bonjour,

ce site est vraiment très bien - merci beaucoup.

Est-ce qu'il serait possible d'avoir un alignement des courbes France, Italie, Espagne et UK en prenant comme en alignant les dates du confinement total pour le nombre de cas et le nombre de décés ?

Premièr graphe : alignement des dates et conservation des valeurs absolues

Deuxième graphe : alignement des dates et prendre comme base 100 les valeurs lors des confinements avec les accroissements relatifs en fonction du temps.

Cela pourrait être une base pour l'analyse de l'impact du confinement en fonction des pays et aussi pour l'analyse de la pertinence du choix de la date de confinement.

Merci

**Comment by rozierguillaume** [comment]
Salut,

Merci beaucoup pour ce retour. Très bonne idée en effet.

Aurais-tu une liste des dates de confinement ? Si c’est juste pour UK/FR/IT/ES je peux le faire moi, mais si tu souhaites que je le fasse pour plus de pays il me faudrait une liste.

Merci,

Bien cordialement,

Guillaume Rozier

**Comment by Mat-GH** [comment]
En fait, dans un premier temps ce serait intéressant de faire une comparaison juste entre IT/SP/FR/UK.

Trop de pays pourrait rendre complexe une comparaison.

A+
Marc

**Comment by Mat-GH** [comment]
Pour info, j'ai fait un graphe moyenne mobile 2 jours sur le nombre de cas en plus par jour en Italie. On voit 2 bosses. Peut-être est-ce du aux 2 dates de confinement (Italie du nord et Italie du sud)

**Comment by rozierguillaume** [comment]
Ah intéressant !
Si tu veux tu peux faire un merge request sur mon dépôt pour l’ajouter.

Je vais essayer de prendre 5 min aujourd’hui pour faire le graphe que tu m’as demandé.

Bien cordialement,

Guillaume Rozier

**Comment by sbonaime** [comment]
Bonjour,
Est-ce qu'il serait aussi possible d'avoir un graph avec des courbes (pas de bar) avec les décès par jour et sur la meme figure le nb de personnes en réanimation ? Et aussi si possible les dérivée de ces courbes qui montreraient la vitesse d'augmentation ou de diminution. 
Merci

**Comment by Mat-GH** [comment]
Euh je ne suis pas sûr de bien savoir faire un merge request 


Je met le fichier en pièce jointe. 


Les données sont issues du site : https://www.eficiens.com/coronavirus-statistiques 

----- Mail original -----

De: "Guillaume Rozier" <notifications@github.com> 
À: "rozierguillaume/covid-19" <covid-19@noreply.github.com> 
Cc: "Mat-GH" <m.touboul@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 1 Avril 2020 12:11:16 
Objet: Re: [rozierguillaume/covid-19] Alignement à partir du confinement total (#1) 


Ah intéressant ! 
Si tu veux tu peux faire un merge request sur mon dépôt pour l’ajouter. 

Je vais essayer de prendre 5 min aujourd’hui pour faire le graphe que tu m’as demandé. 

Bien cordialement, 

Guillaume Rozier

**Comment by Mat-GH** [comment]
Voici le graphe

![Italie - Nombre de cas en plus chaque jour - moyenne mobile 2 jours](https://user-images.githubusercontent.com/52506240/78127407-6a4fbd00-7414-11ea-9f69-631f651c5b8a.png)

**Comment by Mat-GH** [comment]
Un lien qui donne des informations sur les profils de confinement par pays : https://www.google.com/covid19/mobility/
