### ISSUE TITLE
Incorrect scale for daily death of France on international dashboard

### ISSUE THREAD

**Issue by chocopoule** [rozierguillaume/covid-19#6]
Hello,

I think the scale is incorrect for France (more than 800 cases):
![image](https://user-images.githubusercontent.com/1777138/97361187-7c58e780-189f-11eb-91e6-bd56a1f144d6.png)

French dashboard for reference (around 500 cases):
![image](https://user-images.githubusercontent.com/1777138/97361161-7531d980-189f-11eb-9841-118ed3b8e979.png)

**Comment by rozierguillaume** [comment]
Hello,

Thank you for your email. 
The world Dashboard includes every death of Covid. The France dashboard only includes deaths in hospitals (for many reasons, including data quality). So the scale is right. 

Thank you,
Guillaume

**Comment by chocopoule** [comment]
Thanks for the reply (and for this useful website)
