### ISSUE TITLE
Synchronisation du temps entre les subplots

### ISSUE THREAD

**Issue by RomainTT** [rozierguillaume/covid-19#7]
Sur cette image:

![image](https://user-images.githubusercontent.com/12847715/97961568-de3fb280-1db3-11eb-8018-3cd525878227.png)

Le temps n’est pas à la même échelle ni aux mêmes limites sur chaque graphique. Cela complexifie la comparaison.

Il me semble qu’il suffit de rajouter `shared_xaxes=True` à `make_subplots` comme c’est décrit [dans la doc de plotly](https://plotly.com/python/subplots/#subplots-with-shared-xaxes).

**Comment by RomainTT** [comment]
Je t’aurais bien fait une PR, mais sincèrement le dépôt est dans un état trop chaotique pour moi.

**Comment by rozierguillaume** [comment]
Merci pour la suggestion !
C'est fait. Les graphiques sont désormais synchronisés.

Par ailleurs, j'ai ajouté les admissions à l'hôpital et en réa.

Oui, le code n'est clairement pas aussi bien organisé que j'aurais aimé. À ma décharge, je n'ai jamais imaginé que le projet atteigne cette taille. J'essayerai de le ranger si j'ai un peu de temps à l'avenir.
